VaccineManagementMVC/Controllers/AdminController.cs
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using VaccineManagementAPI.Models;

namespace VaccineManagementMVC.Controllers
{
    public class AdminController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:44387/api");
        HttpClient client;
        public AdminController()
        {
            client = new HttpClient();
            client.BaseAddress = baseAddress;
        }
        // GET: Admin
        public ActionResult Index()
        {
            List<User> users = new List<User>();
            HttpResponseMessage response = client.GetAsync(client.BaseAddress + "/user").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                users = JsonConvert.DeserializeObject<List<User>>(data);
            }
            return View(users);
        }
       
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(User user)
        {
            string data = JsonConvert.SerializeObject(user);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync(client.BaseAddress + "/User", content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(FormCollection collection)
        {
            List<Admin> l = new List<Admin>();
            HttpResponseMessage response = client.GetAsync(client.BaseAddress + "/Admin").Result;
            if (response.IsSuccessStatusCode)
            {
                String Data = response.Content.ReadAsStringAsync().Result;
                l = JsonConvert.DeserializeObject<List<Admin>>(Data);
            }
            string username = Request["email"].ToString();
            string password = Request["password"].ToString();
            var found = l.Find(x => x.AdminEmail == username);
            if (found != null)
            {
                if (found.AdminPassword == password)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Msg = "Incorrect password";
                }
            }
            else
            {
                ViewBag.Msg = "Admin not Found";
            }


            return View();
        }
        public ActionResult Edit(int id)
        {
            User l = new User();
            HttpResponseMessage response = client.GetAsync(client.BaseAddress + "/user/" + id).Result;
            if (response.IsSuccessStatusCode)
            {
                String Data = response.Content.ReadAsStringAsync().Result;
                l = JsonConvert.DeserializeObject<User>(Data);
            }
            return View(l);
        }
        [HttpPost]
        public ActionResult Edit(User model)
        {
            string data = JsonConvert.SerializeObject(model);
            StringContent Content = new StringContent(data, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PutAsync(baseAddress + "/user/" + model.UserId, Content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Delete(int id)
        {
            User l = new User();
            HttpResponseMessage response = client.DeleteAsync(baseAddress + "/user/" + id).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Search(string searching)
        {
            List<User> users = new List<User>();
            HttpResponseMessage response = client.GetAsync(client.BaseAddress + "/user").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                users = JsonConvert.DeserializeObject<List<User>>(data);
            }

            return View(users.Where(x => x.Name.Contains(searching) || searching == null).ToList());
        }
        public ActionResult VaccinationDetails(int id)
        {
            User user = new User();
            HttpResponseMessage response = client.GetAsync(client.BaseAddress + "/user/"+id).Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                user = JsonConvert.DeserializeObject<User>(data);
            }

            return View(user.Slots);
        }
       

    }
}

VaccineManagementMVC/Controllers/SlotController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using VaccineManagementAPI.Models;

namespace VaccineManagementMVC.Controllers
{
    public class SlotController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:44387/api");
        HttpClient client;
        public SlotController()
        {
            client = new HttpClient();
            client.BaseAddress = baseAddress;
        }
        public ActionResult Index()
        {
            List<Slot> s = new List<Slot>();
            HttpResponseMessage response = client.GetAsync(client.BaseAddress + "/slot").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                s = JsonConvert.DeserializeObject<List<Slot>>(data);
            }
            return View(s);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Slot slot)
        {
            string data = JsonConvert.SerializeObject(slot);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync(client.BaseAddress + "/slot", content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Edit(int id)
        {
           Slot s = new Slot();
            HttpResponseMessage response = client.GetAsync(client.BaseAddress + "/slot/" + id).Result;
            if (response.IsSuccessStatusCode)
            {
                String Data = response.Content.ReadAsStringAsync().Result;
                s = JsonConvert.DeserializeObject<Slot>(Data);
            }
            return View(s);
        }
        [HttpPost]
        public ActionResult Edit(Slot model)
        {
            string data = JsonConvert.SerializeObject(model);
            StringContent Content = new StringContent(data, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PutAsync(baseAddress + "/slot/" + model.SlotId, Content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Delete(int id)
        {
            Slot l = new Slot();
            HttpResponseMessage response = client.DeleteAsync(baseAddress + "/Slot/" + id).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

VaccineManagementMVC/Views/Admin/Create.cshtml
@model VaccineManagementAPI.Models.User

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<!--<-->@*h2>Create</h2>*@

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4 style="font-weight:bold;margin-left:300px;">Add User</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AadhaarNo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AadhaarNo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AadhaarNo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />

        </div>
    </div>
</div>
    <div>

        <p>
            <a style=" background-color:#11f413; color: white; ">@Html.ActionLink("Back", "Index") </a>

        </p>
    </div>


}

VaccineManagementMVC/Views/Admin/Delete.cshtml
@model VaccineManagementAPI.Models.User

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AadhaarNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AadhaarNo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VaccineManagementMVC/Views/Admin/Index.cshtml
@model IEnumerable<VaccineManagementAPI.Models.User>

@*@{
        ViewBag.Title = "Index";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }*@

@*<h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table" class="table table-bordered table-hover table-sm">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AadhaarNo)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AadhaarNo)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.UserId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.UserId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.UserId })
                </td>
            </tr>
        }

    </table>*@




@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout2.cshtml";
    string[] TableHeaders = new string[] {"Name"
                        ,"Password"
                        ,"Age"
                        ,"PhoneNo"
                        ,"AadhaarNo",
                        "Edit/Delete"
                        };
}

<marquee style="color:black;font-weight:bold;"><h5>Hi admin!,This is the Users List,You can Add ,Edit,Delete,Update</h5></marquee>

<p>
    <button style="border-radius: 30px; border: none; padding: 15px 20px; background-color:#46cead; color: white;margin-top:30px; ">@Html.ActionLink("Add Users", "Create") </button>
    <button style="border-radius: 30px; border: none; padding: 15px 20px; background-color: #46cead; color: white; margin-top: 30px; float: right ">@Html.ActionLink("Add Slots", "Index", "Slot", null, null) </button>
</p>

@*<div class="container top">
    <div class="search-container">
        <input type="text" name="search" placeholder="Search..." class="search-input">
        <a href="@Url.Action("Search", "Admin" , new {Searchi}) "class="search-btn">
            <i class="fas fa-search"></i>
        </a>
    </div>
</div>*@

<div style="margin-left:400px;">
    @using (Html.BeginForm("Search", "Admin", FormMethod.Get))
    {
        @Html.TextBox("Searching")
        <input type="submit" value="Search" />
    }
</div>

<style>
    .text-red {
        color: red;
    }
</style>
<div class="table" style="text-align:center;margin-top:70px;">
    <table id="myTable" class="table table-bordered table-hover table-sm">
        <thead style="background-color:#118ee8;color:white;">
            <tr style="align-items:center;">
                @{
                    foreach (var head in TableHeaders)
                    {
                        <th style="text-align:center;">
                            @head
                        </th>
                    }
                }
            </tr>
        </thead>

        <tbody>
            @{
                if (Model != null)
                {
                    foreach (var Data in Model)
                    {
                        <tr>
                            <td style="background-color:#b3daf6;">@Data.Name</td>
                            <td style="background-color:#e8eff4">@Data.Password</td>
                            <td style="background-color:#b3daf6;">@Data.Age</td>
                            <td style="background-color:#e8eff4">@Data.PhoneNo</td>
                            <td style="background-color:#b3daf6;">@Data.AadhaarNo</td>

                            <td style="background-color:#e8eff4">
                                <p data-placement="top" data-toggle="tooltip" title="Edit">
                                    <button class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit"><span class="glyphicon glyphicon-pencil"></span>@Html.ActionLink("..", "Edit", new { id = Data.UserId })</button> <button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete">
                                        <span class="glyphicon glyphicon-trash"></span> @Html.ActionLink("..", "Delete", new { id = Data.UserId })
                                    </button>
                                    <button class="btn btn-success btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete">
             <span class="glyphicon glyphicon-check"></span> @Html.ActionLink("..", "VaccinationDetails", new { id = Data.UserId })
        </button>
                                </p>

                            </td>


                        </tr>
                    }
                }
            }
        </tbody>

    </table>
</div>

VaccineManagementMVC/Views/Admin/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
@*<head>
        <meta name="viewport" content="width=device-width" />
        <title>Login</title>
    </head>
    <body>
        <div>
        </div>
    </body>*@
<head>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
          crossorigin="anonymous" />

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
            crossorigin="anonymous"></script>
    <style>
    .divider:after,
    .divider:before {
      content: "";
      flex: 1;
      height: 1px;
      background: #eee;
    }
    .h-custom {
      height: calc(100% - 73px);
    }
    @*@media (max-width: 450px) {
      .h-custom {
        height: 100%;
      }*@
    img{
        border-radius: 5%;
    }

    </style>
</head>
<marquee><h1>Please Enter Valid EmailId and Password</h1></marquee>
<body style="background: linear-gradient(120deg,#a01942,#8e44ad)">
    <section class="vh-100" style="background-color:white;">
        <div class="container-fluid h-custom">
            <div class="row d-flex justify-content-center align-items-center h-100">

                <div class="col-md-9 col-lg-6 col-xl-5">
                    <span class="rounded">
                        <img src="https://www.avepoint.com/blog/wp-content/uploads/2021/10/system-administrator-software-developer-working-on-laptop-computer-in-vector-id1296795051.jpg"
                             class="img-fluid" alt="Sample image" style="height:auto;width:auto" />
                    </span>
                </div>
                <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                    @using (Html.BeginForm("Login", "Admin",
new { ReturnUrl = ViewBag.ReturnUrl },
FormMethod.Post, new { @class = "card-body cardbody-color p-lg-5" }))
                    {
                        @Html.AntiForgeryToken()
                        <h6 style="color:red" class="text-center">@ViewBag.msg</h6>
                        @*<div class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start" style="font-weight:bold">
                                <p class="lead fw-normal mb-0 me-3">Sign in with</p>

                            </div>*@

                        @*<div class="divider d-flex align-items-center my-4">
                                <p class="text-center fw-bold mx-3 mb-0">Or</p>
                            </div>*@

                        <!-- Email input -->
                        <div class="form-outline mb-4">
                            <label class="form-label" for="form3Example3"><b>Email Id</b></label>
                            <input type="email"
                                   id="form3Example3" name="email"
                                   class="form-control form-control-lg"
                                   placeholder="Enter a valid Email Id" required />
                        </div>
                        <!-- Password input -->
                        <div class="form-outline mb-3">
                            <label class="form-label" for="form3Example4"><b>Password</b></label>
                            <input type="password"
                                   id="pass" name="password"
                                   class="form-control form-control-lg"
                                   placeholder="Enter password" required  @*pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"*@/>
                            <span id="span" style="color:red"></span>
                        </div>

                        <br />
                        
                        <!--<div class="d-flex justify-content-between align-items-center">-->
                            <!-- Checkbox -->

                            <!--<a href="#!" class="text-body">Forgot password?</a>
                        </div>-->

                        <div class="text-center text-lg-start mt-4 pt-2">
                            <button type="submit"
                                    class="btn btn-primary btn-lg"
                                    style="padding-left: 2.5rem; padding-right: 2.5rem">
                                Login
                            </button>
                            @* <p class="small fw-bold mt-2 pt-1 mb-0">
                                    Don't have an account?
                                    <a href="#!" class="link-danger">Register</a>
                                </p>*@
                        </div>
                    }
                </div>
            </div>
        </div>

    </section>
    <script>
        var input = document.getElementById('pass');
        input.oninvalid = function (event) {
          //  event.target.setCustomValidity('Username should only contain lowercase letters. e.g. john');
            var ans = document.getElementById("span");
            ans.innerHTML = "Minimum eight characters, at least one uppercase letter, one lowercase letter and one number";
        }
        
    </script>
</body>
</html>

VaccineManagementMVC/Views/Admin/Search.cshtml
@model IEnumerable<VaccineManagementAPI.Models.User>

@*@{
        ViewBag.Title = "Index";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }*@

@*<h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table" class="table table-bordered table-hover table-sm">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AadhaarNo)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AadhaarNo)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.UserId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.UserId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.UserId })
                </td>
            </tr>
        }

    </table>*@




@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout2.cshtml";
    string[] TableHeaders = new string[] {"Name"
                        ,"Password"
                        ,"Age"
                        ,"PhoneNo"
                        ,"AadhaarNo",
                        "Edit/Delete"
                        };
}

<marquee style="color:black;font-weight:bold;"><h5>Hi admin!,This is the Users List,You can Add ,Edit,Delete,Update</h5></marquee>

<p>
    <button style="border-radius: 30px; border: none; padding: 15px 20px; background-color:#46cead; color: white;margin-top:30px; ">@Html.ActionLink("Add Users", "Create") </button>
    <button style="border-radius: 30px; border: none; padding: 15px 20px; background-color: #46cead; color: white; margin-top: 30px; float: right ">@Html.ActionLink("Add Slots", "Index", "Slot", null, null) </button>
</p>

@*<div class="container top">
        <div class="search-container">
            <input type="text" name="search" placeholder="Search..." class="search-input">
            <a href="@Url.Action("Search", "Admin" , new {Searchi}) "class="search-btn">
                <i class="fas fa-search"></i>
            </a>
        </div>
    </div>*@

<div style="margin-left:400px;">
    @using (Html.BeginForm("Search", "Admin", FormMethod.Get))
    {
        @Html.TextBox("Searching")
        <input type="submit" value="Search" />
    }
</div>

<style>
    .text-red {
        color: red;
    }
</style>
<div class="table" style="text-align:center;margin-top:70px;">
    <table id="myTable" class="table table-bordered table-hover table-sm">
        <thead style="background-color:#118ee8;color:white;">
            <tr style="align-items:center;">
                @{
                    foreach (var head in TableHeaders)
                    {
                        <th style="text-align:center;">
                            @head
                        </th>
                    }
                }
            </tr>
        </thead>

        <tbody>
            @{
                if (Model != null)
                {
                    foreach (var Data in Model)
                    {
                        <tr>
                            <td style="background-color:#b3daf6;">@Data.Name</td>
                            <td style="background-color:#e8eff4">@Data.Password</td>
                            <td style="background-color:#b3daf6;">@Data.Age</td>
                            <td style="background-color:#e8eff4">@Data.PhoneNo</td>
                            <td style="background-color:#b3daf6;">@Data.AadhaarNo</td>

                            <td style="background-color:#e8eff4">
                                <p data-placement="top" data-toggle="tooltip" title="Edit">
                                    <button class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit"><span class="glyphicon glyphicon-pencil"></span>@Html.ActionLink("..", "Edit", new { id = Data.UserId })</button> <button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete">
                                        <span class="glyphicon glyphicon-trash"></span> @Html.ActionLink("..", "Delete", new { id = Data.UserId })
                                    </button>
                                    <button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete">
                                        <span class="glyphicon glyphicon-check"></span> @Html.ActionLink("..", "VaccinationDetails", new { id = Data.UserId })
                                    </button>
                                </p>

                            </td>


                        </tr>
                    }
                }
            }
        </tbody>

    </table>
</div>